steps:
  - task: ArchiveFiles@2
    name: archiveFiles
    displayName: Create Build Artifact
    condition: eq(variables.isStable, 'True')
    inputs:
      rootFolderOrFile: $(projectRoot)
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    name: publishBuildArtifacts
    displayName: Publish Build Artifacts
    condition: eq(variables.isStable, 'True')
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: drop
      publishLocation: Container
