parameters:
  - name: bicepDir
    displayName: Directory containing Folders with Bicep Templates
    type: string
    default: 'IaC/bicep/deploy'
  - name: bicepTemplateDir
    displayName: Directory containing the main.bicep
    type: object
    default:
      - 'acr'
      - 'kv'
  - name: bicepParameter
    displayName: Used in some templates to change Resource Name or other variables
    type: string
    values:
      - dev
      - stg
      - prod
  - name: resourceGroupName
    displayName: Name of the Resource Group where templates will be deployed to
    type: string
    default: $(resourceGroupName)
  - name: azureSubscription
    displayName: Name of the ARM-Service Connection
    type: string
    default: $(azureSubscription)
  - name: location
    displayName: Location where the Resources will be deployed to
    type: string
    default: $(location)

stages:
  - stage: bicep
    displayName: Bicep
    jobs:
      - job: generator
        steps:
          - task: PowerShell@2
            name: mtrx
            env:
              bicepDir: ${{ parameters.bicepDir }}
              bicepParameter: ${{ parameters.bicepParameter }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              azureSubscription: ${{ parameters.azureSubscription }}
              location: ${{ parameters.location }}
            inputs:
              targetType: filePath
              filePath: scripts/New-BicepMatrix.ps1

      - job: runner
        dependsOn: generator
        strategy:
          matrix: $[ dependencies.generator.outputs['mtrx.legs'] ]
        steps:
        - script: |
            echo '##vso[task.setVariable variable=bicepDir]$BICEPDIR'
            echo '##vso[task.setVariable variable=bicepTemplateDir]$BICEPTEMPLATEDIR'
            echo '##vso[task.setVariable variable=bicepParameter]$BICEPPARAMETER'
            echo '##vso[task.setVariable variable=resourceGroupName]$RESOURCEGROUPNAME'
            echo '##vso[task.setVariable variable=azureSubscription]$AZURESUBSCRIPTION'
            echo '##vso[task.setVariable variable=location]$LOCATION'
          displayName: $(bicepTemplateDir)
        - template: jobs/steps/bicep_steps.yml
          parameters:
            bicepDir: $[ variables['bicepDir'] ]
            bicepTemplateDir: $[ variables['bicepTemplateDir'] ]
            bicepParameter: $[ variables['bicepParameter'] ]
            resourceGroupName: $[ variables['resourceGroupName'] ]
            azureSubscription: $[ variables['azureSubscription'] ]
            location: $[ variables['location'] ]
        - script: export
          displayName: output export
        - script: env
          displayName: output env
        - script: set
          displayName: output set
        # - template: '../$(templatePath)/main.parameters.yml'
      # - ${{ each value in parameters.bicepTemplateDir }}:
      #     - template: jobs/bicep_jobs.yml
      #       parameters:
      #         bicepDir: ${{ parameters.bicepDir }}
      #         bicepTemplateDir: ${{ value }}
      #         bicepParameter: ${{ parameters.bicepParameter }}
      #         resourceGroupName: ${{ parameters.resourceGroupName }}
      #         azureSubscription: ${{ parameters.azureSubscription }}
      #         location: ${{ parameters.location }}
